In [1]:
import torch
import torch.nn as nn

In [3]:
prediction = torch.randn(4, 5)
print(prediction)

tensor([[ 0.2038,  0.4880, -0.9008, -0.1254, -1.6854],
        [-0.9293,  0.5665,  0.9608,  0.0460, -0.1810],
        [-0.5861,  1.9265, -0.6222,  1.2896, -1.0495],
        [ 3.1029,  2.6405, -1.5447,  1.7703,  1.9656]])


In [6]:
#mean sqaured error
label = torch.randn(4, 5)

In [17]:
mse = nn.MSELoss(reduction='mean')

In [18]:
loss = mse(prediction, label)

In [19]:
loss

tensor(3.9685)

In [21]:
#from scratch
((prediction-label)**2).mean()

tensor(3.9685)

In [22]:
prediction

tensor([[ 0.2038,  0.4880, -0.9008, -0.1254, -1.6854],
        [-0.9293,  0.5665,  0.9608,  0.0460, -0.1810],
        [-0.5861,  1.9265, -0.6222,  1.2896, -1.0495],
        [ 3.1029,  2.6405, -1.5447,  1.7703,  1.9656]])

In [23]:
label = torch.zeros(4, 5).random_(0, 2)

In [24]:
label

tensor([[1., 0., 0., 1., 1.],
        [0., 1., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0.]])

In [25]:
sigmoid = nn.Sigmoid()
bce = nn.BCELoss(reduction='mean')

In [26]:
bce(sigmoid(prediction), label)

tensor(1.1876)

In [30]:
bce_ll = nn.BCEWithLogitsLoss(reduction='mean')
bce_ll(prediction, label)

tensor(1.1876)

In [38]:
import numpy as np
x = prediction.numpy()
y = label.numpy()
print(y)
print(x)

[[1. 0. 0. 1. 1.]
 [0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]
[[ 0.20380929  0.488043   -0.9007971  -0.12539648 -1.6854314 ]
 [-0.92934406  0.56651026  0.9607943   0.04595039 -0.18095078]
 [-0.5861091   1.9265486  -0.6222258   1.2896003  -1.0494517 ]
 [ 3.1029122   2.6405087  -1.5447264   1.7702743   1.965559  ]]


In [45]:
#implementing sigmoid activation
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [46]:
x = sigmoid(x)

In [47]:
loss_values = []
for i in range(len(y)):
    batch_loss = []
    for j in range(len(y[0])):
        if (y[i][j] == 1):
            loss = -np.log(x[i][j])
        else:
            loss = -np.log(1-x[i][j])
        batch_loss.append(loss)
    loss_values.append(batch_loss)
print(np.mean(loss_values))

0.8779683985949331
